import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getContent,findImage} from '@/lib/content';
import {canonicalUrl,siteHref,readyPractice} from '@/lib/ecosystem';
import {money} from '@/lib/format';
import {Photo} from '@/components/photo';
import {InquiryButton} from '@/components/inquiry';
import {ProgramPackages} from '@/components/program-packages';
export async function generateStaticParams(){const content=await getContent();return [...content.rooms,...content.practiceSessions].map(item=>({slug:item.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const content=await getContent();const item=[...content.rooms,...content.practiceSessions].find(item=>item.slug===slug);return {title:item?.title,description:item?.description,alternates:{canonical:canonicalUrl('hub',slug)}};}
export default async function HubDetail({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const content=await getContent();const room=content.rooms.find(item=>item.slug===slug);const session=content.practiceSessions.find(item=>item.slug===slug);
 if(room)return <div className="container hub-detail"><section className="hub-detail-opening"><div><Link className="breadcrumb" href={siteHref('hub','#spaces')}>Усі простори</Link><h1>{room.title}</h1><p className="lead">{room.description}</p><p className="room-detail-price">{money(room.pricePerHour)} <span>/ год</span></p><p className="muted">{room.area?`${room.area} м² · `:''}Від {room.minimumMinutes} хв</p><Link className="button" href={siteHref('hub',`booking?room=${room.bookingKey}`)}>Перевірити вільний час</Link>{room.equipmentNote&&<p className="equipment-note">{room.equipmentNote}</p>}</div><figure><Photo image={findImage(content,room.imageId)} priority/></figure></section><section className="room-detail-body"><div><h2>Для вашого формату</h2><ul className="room-features">{room.features.map(feature=><li key={feature}>{feature}</li>)}</ul><p className="muted">Остаточна вартість залежить від часу та тривалості. Тариф і доступність показує календар бронювання.</p></div><div><h2>Як нас знайти</h2><p>{content.hub.address}<br/>{content.hub.arrival}</p><a href={content.hub.mapsUrl} className="text-link" target="_blank" rel="noreferrer">Прокласти маршрут</a></div></section>{room.galleryImageIds.filter(id=>id!==room.imageId).map(id=><figure className="room-extra-photo" key={id}><Photo image={findImage(content,id)} natural/><figcaption>{findImage(content,id).credit}</figcaption></figure>)}</div>;
 if(!session)notFound();
 const ready=readyPractice(session);const space=content.rooms.find(room=>room.id===session.roomId)!;const offering=ready&&session.enrollmentOfferingId?content.offerings.find(item=>item.id===session.enrollmentOfferingId):undefined;const program=offering?content.programs.find(item=>item.id===offering.programId):undefined;
 return <div className="container hub-detail practice-detail"><section className="hub-detail-opening"><div><p className="eyebrow">Практика · Київ</p><h1>{session.title}</h1><p className="lead">{session.description}</p>{ready?<p className="room-detail-price">{money(session.price!)} <span>· {session.duration}</span></p>:<p className="practice-stage">Готуємо формат · деталі після підтвердження</p>}<InquiryButton practiceSessionId={session.id} title={ready?'Запит про контент-практику':'Повідомити про старт практики'}>{ready?'Запитати про практику':'Повідомити про старт'}</InquiryButton><p className="practice-independent">Окрема платна практика. Участь у ній необов’язкова для проходження онлайн-курсу.</p></div><figure><Photo image={findImage(content,session.imageId)} priority/></figure></section>{offering&&program&&<ProgramPackages offering={offering} program={program}/>}
 <section className="room-detail-body"><div><h2>{ready?'Як проходитиме практика':'Практика навколо вашого бренду'}</h2><p>Зйомка для власного експертного бренду з підтримкою викладача. Розберемо ваш задум і застосуємо знання з курсу до конкретного контенту.</p>{ready?<dl className="practice-facts"><div><dt>Дата</dt><dd>{new Intl.DateTimeFormat('uk-UA',{dateStyle:'long',timeZone:'Europe/Kyiv'}).format(new Date(session.date!))}</dd></div><div><dt>Група</dt><dd>До {session.capacity} учасників</dd></div></dl>:<p className="muted">Підтверджуємо викладача, тривалість, розмір групи, оснащення та вартість. Заявка означає інтерес до анонсу й не створює бронювання.</p>}</div><div><h2>Де зустрінемось</h2><p>{content.hub.address}<br/>{content.hub.arrival}</p><p className="muted">Простір ProPhoto Hub · {space.title}</p></div></section>
 {ready&&<section className="practice-delivery">{[['Що підготувати',session.preparation],['Обладнання',session.equipment],['Що створите',session.deliverables]].map(([title,items])=><div key={title as string}><h2>{title as string}</h2><ul>{(items as string[]).map(item=><li key={item}>{item}</li>)}</ul></div>)}</section>}
 <section className="practice-next"><h2>Почніть зі знань</h2><p>«Інста, яка продає» — онлайн-курс зі створення контенту для свого експертного бренду.</p><a href={siteHref('academy','course-smm-instagram')} className="text-link" data-ecosystem-target="academy">Переглянути курс</a></section></div>;
}
